name         'fernandoalmeida-java'
version      '0.0.1'
source       'https://github.com/fernandoalmeida/puppet-java.git'
author       'Fernando Almeida'
license      'Apache License, Version 2.0'
summary      'A Puppet module for installing and configuring Java'
description  'A Puppet module for installing and configuring Java'
project_page 'https://github.com/fernandoalmeida/puppet-java'
